### PR TITLE
開発者継続するために、不要ファイルを整理

### PR DESCRIPTION
**Pull request by Yasu-umi**
- 開発者継続するために、不要ファイルを整理
  - testは動かなかったので一旦削除
  - release機能は作り直すので一旦削除
  - CIはgithub actionsに移行(元のCIは見れなかった)

### CODE REVIEW

**Comment by Yasu-umi** [comment]
sorry, i failed to create pull req to my repo...
if you're interested in update this repo, i'll re-open pull req.
i plan to update 0.0.3
- use tox for flake8 3 & 4, python 3.7-3.10
- test
- cache dir option
- release by github actions

**Comment by jnoortheen** [comment]
I just saw the changed files. I'd be happy to accept any new features. Here it seems to be around tooling. I think we can stick to the current tools for now.

**Comment by Yasu-umi** [comment]
thanks for quick response !
i hope to use flake8-cached for my project(python3.10, flake8 v4).
happily, after some modification pyproject.toml & custom build, it works! but poetry builds flake8-cached which requires flake8 v3. and, i don't know how to build multi major version requirement pkgs (flake8 v3 & v4)...

**Comment by jnoortheen** [comment]
I have updated the pyproject.toml. Please try to use the git version and let me know if that works

**Comment by Yasu-umi** [comment]
i checked it's works for flake8 v4 & python 3.10 ! please release pypi as v0.0.3 🙏

**Comment by jnoortheen** [comment]
done !

**Pull request closed without merging**
